-- ============================================================
-- Alumini — Auth Module Tables
-- Migration: 002_auth_module.sql
--
-- Tables owned by apps/backend/src/modules/auth (see SPEC.md §15.3 —
-- "Each module owns its database tables. Cross-module communication
-- via events only.").
--
--   sessions            — refresh token tracking, powers the 7-day JWT
--                          session (appConfig.JWT_EXPIRY_DAYS) and the
--                          concurrent-device limit (appConfig.SESSION_MAX_DEVICES)
--   mfa_totp_secrets    — one TOTP secret per user (authenticator app MFA)
--   mfa_sms_challenges  — short-lived SMS OTP codes (MFA fallback, non-admins only)
--
-- profiles.mfa_enabled / profiles.mfa_method (see 001_initial_schema.sql)
-- remain the single source of truth for "is MFA on, and via which method" —
-- these tables hold the secrets/challenges that back that flag.
-- ============================================================

-- ============================================================
-- 1. SESSIONS (refresh token tracking)
-- ============================================================

CREATE TABLE public.sessions (
  id                 uuid        PRIMARY KEY DEFAULT uuid_generate_v4(),
  user_id            uuid        NOT NULL REFERENCES public.profiles(id) ON DELETE CASCADE,
  refresh_token_hash text        NOT NULL UNIQUE,  -- SHA-256 hash — the raw token is never stored
  user_agent         text,
  ip_address         inet,
  created_at         timestamptz NOT NULL DEFAULT now(),
  last_used_at       timestamptz NOT NULL DEFAULT now(),
  expires_at         timestamptz NOT NULL,
  revoked_at         timestamptz,
  revoked_reason     text
);

COMMENT ON TABLE public.sessions IS
  'One row per issued refresh token (device/session). A session is "active" when
   revoked_at IS NULL AND expires_at > now(). Refresh tokens rotate on every
   POST /auth/refresh — the row is updated in place, not re-inserted.
   SPEC.md §4.3: concurrent session limit is 5 devices per account
   (appConfig.SESSION_MAX_DEVICES) — the oldest active session is revoked
   to make room for a new one once the cap is reached.';
COMMENT ON COLUMN public.sessions.refresh_token_hash IS
  'SHA-256 hex digest of the refresh JWT. Storing only the hash means a
   database read alone can never be used to impersonate a session.';

CREATE INDEX sessions_user_active_idx
  ON public.sessions(user_id, revoked_at, expires_at);

ALTER TABLE public.sessions ENABLE ROW LEVEL SECURITY;

-- Users can see their own sessions (e.g. a future "manage devices" screen)
CREATE POLICY "sessions_read_own"
  ON public.sessions FOR SELECT
  USING (user_id = auth.uid());

-- All writes (create, rotate, revoke) go through the API's service-role
-- client only — a client JWT can never forge, extend, or revive a session row.
CREATE POLICY "sessions_insert_service_only"
  ON public.sessions FOR INSERT
  WITH CHECK (false);

CREATE POLICY "sessions_update_service_only"
  ON public.sessions FOR UPDATE
  USING (false);

-- ============================================================
-- 2. MFA TOTP SECRETS
-- ============================================================

CREATE TABLE public.mfa_totp_secrets (
  user_id      uuid        PRIMARY KEY REFERENCES public.profiles(id) ON DELETE CASCADE,
  secret       text        NOT NULL,   -- base32 TOTP secret (speakeasy)
  confirmed    boolean     NOT NULL DEFAULT false,
  created_at   timestamptz NOT NULL DEFAULT now(),
  confirmed_at timestamptz
);

COMMENT ON TABLE public.mfa_totp_secrets IS
  'One TOTP secret per user, generated by GET /auth/mfa/setup. confirmed=false
   until the user proves possession of the secret via POST /auth/mfa/verify
   (or a later re-enrolment overwrites it — see the upsert in AuthService).
   No client ever reads this table directly — access is service-role only,
   mirroring the institution_codes pattern in 001_initial_schema.sql.';

ALTER TABLE public.mfa_totp_secrets ENABLE ROW LEVEL SECURITY;

CREATE POLICY "mfa_totp_secrets_no_direct_access"
  ON public.mfa_totp_secrets FOR SELECT
  USING (false);

CREATE POLICY "mfa_totp_secrets_no_insert"
  ON public.mfa_totp_secrets FOR INSERT
  WITH CHECK (false);

-- ============================================================
-- 3. MFA SMS CHALLENGES
-- ============================================================

CREATE TABLE public.mfa_sms_challenges (
  id          uuid        PRIMARY KEY DEFAULT uuid_generate_v4(),
  user_id     uuid        NOT NULL REFERENCES public.profiles(id) ON DELETE CASCADE,
  phone       text        NOT NULL,
  code_hash   text        NOT NULL,   -- SHA-256 hash of the OTP — never stored in plaintext
  attempts    integer     NOT NULL DEFAULT 0,
  consumed    boolean     NOT NULL DEFAULT false,
  expires_at  timestamptz NOT NULL,
  created_at  timestamptz NOT NULL DEFAULT now()
);

COMMENT ON TABLE public.mfa_sms_challenges IS
  'Short-lived SMS OTP challenges (appConfig.SMS_OTP_EXPIRY_MINUTES, code length
   appConfig.SMS_OTP_LENGTH). SMS is fallback-only and NOT available to
   school_admin personas — TOTP only (appConfig.ADMIN_MFA_TOTP_ONLY), enforced
   in AuthService before a challenge row is ever created. Service-role access only.';

CREATE INDEX mfa_sms_challenges_user_idx
  ON public.mfa_sms_challenges(user_id, consumed, expires_at);

ALTER TABLE public.mfa_sms_challenges ENABLE ROW LEVEL SECURITY;

CREATE POLICY "mfa_sms_challenges_no_direct_access"
  ON public.mfa_sms_challenges FOR SELECT
  USING (false);

CREATE POLICY "mfa_sms_challenges_no_insert"
  ON public.mfa_sms_challenges FOR INSERT
  WITH CHECK (false);
